import { StyleSheet } from "react-native";

export function getPriorityStyle(priority) {
  if (priority === "HIGH") return styles.priorityHigh;
  if (priority === "ACK") return styles.priorityAck;
  if (priority === "STORE") return styles.priorityStore;
  return styles.priorityTraining;
}

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#07111f",
  },
  appShell: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: "#07111f",
  },
  screenContent: {
    padding: 20,
    paddingBottom: 112,
  },
  homeHero: {
    backgroundColor: "#ffffff",
    borderRadius: 30,
    padding: 24,
    marginBottom: 16,
  },
  badge: {
    width: 66,
    height: 66,
    borderRadius: 22,
    backgroundColor: "#e91f3f",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -1,
  },
  homeEyebrow: {
    color: "#e91f3f",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
    marginBottom: 8,
  },
  homeTitle: {
    color: "#10212b",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: -1.4,
    marginBottom: 8,
  },
  homeSubtitle: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#101d2d",
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  statNumber: {
    color: "#ffffff",
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -1,
  },
  statLabel: {
    color: "#8fa2b6",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  quickCard: {
    backgroundColor: "#101d2d",
    borderRadius: 26,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  sectionHeader: {
    marginTop: 4,
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.6,
    marginBottom: 12,
  },
  primaryButton: {
    backgroundColor: "#e91f3f",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  secondaryButton: {
    backgroundColor: "#eef5f8",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 12,
  },
  secondaryButtonText: {
    color: "#163847",
    fontSize: 16,
    fontWeight: "900",
  },
  headerBlock: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 22,
    marginBottom: 16,
  },
  headerEyebrow: {
    color: "#e91f3f",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
    marginBottom: 8,
  },
  pageTitle: {
    color: "#10212b",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: -1.3,
    marginBottom: 6,
  },
  pageSubtitle: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
  },
  messageCard: {
    backgroundColor: "#101d2d",
    borderRadius: 22,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  messageCardUnread: {
    borderColor: "rgba(233,31,63,0.55)",
    backgroundColor: "#132236",
  },
  messageTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 14,
  },
  messageMetaLeft: {
    flex: 1,
  },
  messageFrom: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  messageTime: {
    color: "#8597aa",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  messageTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.6,
    marginBottom: 6,
  },
  messagePreview: {
    color: "#b8c6d6",
    fontSize: 14,
    lineHeight: 21,
  },
  messageFooterRow: {
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ackText: {
    color: "#ffb3c0",
    fontSize: 12,
    fontWeight: "900",
  },
  ackDoneText: {
    color: "#7ee0a0",
    fontSize: 12,
    fontWeight: "900",
  },
  normalText: {
    color: "#8092a6",
    fontSize: 12,
    fontWeight: "800",
  },
  unreadDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    backgroundColor: "#e91f3f",
  },
  priorityPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  priorityText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  priorityHigh: {
    backgroundColor: "#e91f3f",
  },
  priorityAck: {
    backgroundColor: "#f59e0b",
  },
  priorityStore: {
    backgroundColor: "#0089a7",
  },
  priorityTraining: {
    backgroundColor: "#24556b",
  },
  appHeader: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: {
    color: "#ffffff",
    fontSize: 36,
    lineHeight: 38,
    fontWeight: "600",
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -1,
  },
  headerSubtitle: {
    color: "#9cadbf",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  detailCard: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    padding: 24,
  },
  detailTitle: {
    color: "#10212b",
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -1.2,
    marginTop: 18,
    marginBottom: 8,
  },
  detailMeta: {
    color: "#697b8d",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 22,
  },
  detailBody: {
    color: "#263847",
    fontSize: 17,
    lineHeight: 27,
    marginBottom: 18,
  },
  acknowledgedBox: {
    backgroundColor: "#ecfdf3",
    borderRadius: 18,
    padding: 16,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  acknowledgedBoxTitle: {
    color: "#166534",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 4,
  },
  acknowledgedBoxText: {
    color: "#216b3b",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  emptyCard: {
    backgroundColor: "#101d2d",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  emptyTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 6,
  },
  emptyText: {
    color: "#9cadbf",
    fontSize: 14,
    lineHeight: 21,
  },
  profileCard: {
    backgroundColor: "#101d2d",
    borderRadius: 28,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 28,
    backgroundColor: "#e91f3f",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  profileAvatarText: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "900",
  },
  profileName: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
    marginBottom: 4,
  },
  profileMeta: {
    color: "#9cadbf",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 2,
  },
  profileList: {
    backgroundColor: "#101d2d",
    borderRadius: 24,
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  profileRow: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  profileRowLabel: {
    color: "#b8c6d6",
    fontSize: 14,
    fontWeight: "800",
  },
  profileRowValue: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  bottomTabs: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    backgroundColor: "rgba(16,29,45,0.96)",
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 8,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  tabIconWrap: {
    width: 38,
    height: 34,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  tabIconWrapActive: {
    backgroundColor: "#e91f3f",
  },
  tabIcon: {
    color: "#9cadbf",
    fontSize: 18,
    fontWeight: "900",
  },
  tabIconActive: {
    color: "#ffffff",
  },
  tabLabel: {
    color: "#8fa2b6",
    fontSize: 11,
    fontWeight: "900",
  },
  tabLabelActive: {
    color: "#ffffff",
  },
  tabBadge: {
    position: "absolute",
    right: -4,
    top: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tabBadgeText: {
    color: "#e91f3f",
    fontSize: 10,
    fontWeight: "900",
  },
});
